version: '3.9'
services:
  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  clickonafunnyface:
    build: .
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config: